# Default values for myapp.
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.23"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9113"
  prometheus.io/path: "/metrics"
podLabels:
  app: myapp
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
prometheus:
  monitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    additionalLabels:
      release: prometheus

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
  - name: nginx-config
    configMap:
      name: "{{ include \"myapp.fullname\" . }}-nginx-config"
volumeMounts:
  - name: nginx-config
    mountPath: /etc/nginx/conf.d

nodeSelector: {}
tolerations: []
affinity: {}