loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true

singleBinary:
  enabled: true

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
