apiVersion: v1
kind: Service
metadata:
  name: deploymentapi # This is the service name that other in-cluster apps will use
  labels:
    app: deploymentapi
spec:
  selector:
    app: deploymentapi # Selects pods with the label app: deploymentapi
  ports:
    - protocol: TCP
      port: 8081       # The port the service will listen on
      targetPort: 8081 # The port the container (Spring Boot app) is listening on
  type: ClusterIP # Internal cluster access only. Use NodePort or LoadBalancer for external access.