pipelineStages:
  - docker:
  - match:
      selector: '{app="myapp"}'
      stages:
        - regex:
            expression: ".*"
        - labels:
            app: myapp
            namespace: default
clients:
  - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push