apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-nginx-config
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 80;
      location /stub_status {
        stub_status on;
        allow 127.0.0.1;
        deny all;
      }
    }