apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http # Main application HTTP port
    - port: 9113 # Expose the prometheus exporter port
      targetPort: 9113
      protocol: TCP
      name: metrics # This named port is crucial for ServiceMonitor
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}