{{- if .Values.prometheus.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      interval: {{ .Values.prometheus.monitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.prometheus.monitor.scrapeTimeout | default "10s" }}
      path: /actuator/prometheus
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
{{- end }}